### PR TITLE
I know it is rather forward... (asking for forgiveness, not for permission)

### PR DESCRIPTION
**Pull request by stefek99**
Google Doc with strategy: https://docs.google.com/document/d/1F8ESR6atOfCV2ysOQJTA2peXXGVMY4YLX4t4aBm9nJQ/edit#

I'll also need to fix the `bootstrap` columns and offsets so it looks good in all screen resolutions.
decentraland_and_decentraland_-_token_sale_and_climate_change_is_real____mostly_doing

### CODE REVIEW

**Comment by arimeilich** [comment]
This is the Core Team. We've known each other for years. If you want to be considered you have to actually show results.

**Comment by stefek99** [comment]
> you have to actually show results

> I would like discuss with you my unofficial, "trail basis" capacity

It's difficult to show any actual results while acting in an **unofficial trial basis** capacity, without knowing what are your goals, strategy, vision, etc...

The Google Doc with potential suggestions is constantly growing: https://docs.google.com/document/d/1F8ESR6atOfCV2ysOQJTA2peXXGVMY4YLX4t4aBm9nJQ/edit#

Last night I didn't see any reply on Slack so decided to continue my attendance at the workshop:

image

If you were to reply to that conversation I'd definitely reprioritise and made myself available.

**Comment by stefek99** [comment]
The Google Doc is constantly updating, not sure if you saw that bit:

image

**Comment by stefek99** [comment]
@martriay @arimeilich 

I just saw that https://twitter.com/demibrener was removed from the website.

We live in crazy times - https://twitter.com/stefek99/status/884942446521704448 - someone just raised $60k:

> The UET ICO transparently offers investors no value, so there will be no expectation of gains. 

You are exceptionally solid, that is why I see enormous value of working with you.

So far I didn't receive a single piece of feedback other than _____________ `blank` and it is extremely difficult to speculate...

To have a Skype call could remove fog of mystery, my handle: `mstefanow`, Google Hangouts `email@genesis.re` also FaceTime / WhatsApp `0044 758 629 4279`

____

In my reality more committed, reliable people and access to their networks and talents increases the value of the project and upcoming ICO.

**Pull request closed without merging**
